### PR TITLE
Created base accounts app for user-profiles.

### PR DESCRIPTION
**Pull request by DEVANSH-DVJ**
As of now, there are two apps - users and accounts. I would make them one once everything is decided.

### CODE REVIEW

**Comment by hrshtv** [comment]
Are we going to add email verification during sign up?

**Comment by DEVANSH-DVJ** [comment]
> Are we going to add email verification during sign up?

We would be using Insti ldap servers to get data and avoid sign up of IITB students.  
User model would be finalized on Sunday after Chaithanya contacts Insti sysad.  
We can create a new channel for discussion on user model.

**Comment by hrshtv** [comment]
Some issues:

In edit profile, even after confirming the email for the first time, when I try to edit it again, it again asks for email confirmation.

Messages are not being displayed on the profile page, in fact they are getting displayed on the blog site.

**Comment by DEVANSH-DVJ** [comment]
> In edit profile, even after confirming the email for the first time, when I try to edit it again, it again asks for email confirmation.

The fields will be decided later. Maybe there won't be a need of confirm email, or bio validator.
Accordingly, I would make changes to the model.

**Comment by chaithumcn3** [comment]
> Are we going to add email verification during sign up?

We are going to use SSO verification

**Pull request closed without merging**
