### PR TITLE
Integrating admin interface into users

### PR DESCRIPTION
**Pull request by DEVANSH-DVJ**
I integrated Harshit's work on admin interface into my work on User profile

### CODE REVIEW

**Comment by hrshtv** [comment]
The error was while fetching data (I guess), in profile_json['key']. It happened after I authorized my profile with the app.

**Comment by DEVANSH-DVJ** [comment]
> The error was while fetching data (I guess), in profile_json['key']. It happened after I authorized my profile with the app.

What was the output of line 68 in views.py 'print(profile_json)'

**Comment by DEVANSH-DVJ** [comment]
> > The error was while fetching data (I guess), in profile_json['key']. It happened after I authorized my profile with the app.
> 
> What was the output of line 68 in views.py 'print(profile_json)'

Did you authorize to take all info from gymkhana server or not? (Did you uncheck any boxes when asked to authorize)

**Comment by DEVANSH-DVJ** [comment]
> > > The error was while fetching data (I guess), in profile_json['key']. It happened after I authorized my profile with the app.
> > 
> > 
> > What was the output of line 68 in views.py 'print(profile_json)'
> 
> Did you authorize to take all info from gymkhana server or not? (Did you uncheck any boxes when asked to authorize)

**Comment by hrshtv** [comment]
I did authorize everything. I have not added my room number etc on my gymkhana profile, which lead to a NoneType error.

**Comment by DEVANSH-DVJ** [comment]
> > The error was while fetching data (I guess), in profile_json['key']. It happened after I authorized my profile with the app.
> 
> What was the output of line 68 in views.py 'print(profile_json)'

What is the output of profile_json?

**Comment by hrshtv** [comment]
`user.user_profile.room = profile_json['insti_address']['room'] `  
This causes the error. The output is my profile, with some fields as `None`

**Comment by DEVANSH-DVJ** [comment]
@hrshtv 
Check now, if it works or not...

**Pull request merged**
