### PR TITLE
wiki-new

### PR DESCRIPTION
**Pull request by hrshtv**
This is the draft PR for the new wiki app, which will be made from scratch.

### CODE REVIEW

**Comment by DEVANSH-DVJ** [comment]
Screenshot from 2020-05-04 11-43-50
What did I do wrong?

**Comment by hrshtv** [comment]
Go to the django-admin interface, and create an article with the slug as: `main_page`  
This is the main page/article which loads up on the main page of the wiki.

**Comment by DEVANSH-DVJ** [comment]
Screenshot from 2020-05-04 18-12-51
Make a return for non-admin people if they try to edit or simply remove that edit option for non-admin people.

**Comment by DEVANSH-DVJ** [comment]
image
There is already a 'Second' page there.

So, this is thrown.
image

**Comment by hrshtv** [comment]
Yeah, articles with the same name aren't expected.   
Did you try to edit by going to `wiki/article/edit `directly?

**Comment by DEVANSH-DVJ** [comment]
> Yeah, articles with the same name aren't expected.
> Where do you think such a situation(exact same titles) will arise?
New Article

> Regarding the edit function,
> Did you try to edit by going to `wiki/article/edit `directly?
No, I created two articles using superuser, then changed to a normal person. Then I clicked edit on the main_page article.

**Comment by hrshtv** [comment]
> New Article
  
Yes, but why will someone want to create 2 articles with the exact same title?

> No, I created two articles using superuser, then changed to a normal person. Then I clicked edit on the main_page article.

Are you sure you are a normal user? Because it doesn't show the edit link when I open the main_page as a non-admin.

**Comment by DEVANSH-DVJ** [comment]
> > New Article
> 
> Yes, but why will someone want to create 2 articles with the exact same title?
> 
What if someone made the same article but it is pending approval and you don't know. No errors should be thrown via links atleast.

> > No, I created two articles using superuser, then changed to a normal person. Then I clicked edit on the main_page article.
> 
> Are you sure you are a normal user? Because it doesn't show the edit link when I open the main_page as a non-admin.

If I am an admin then that error shouldn't be thrown anyway.

**Comment by hrshtv** [comment]
If you are an admin then that error shouldn't come, is it coming when you are a admin?   

But if you were the author of the main article, and then you removed yourself as an admin, then you'll still be able to edit it.

**Comment by DEVANSH-DVJ** [comment]
> If you are an admin then that error shouldn't come, is it coming when you are a admin?
> 
> But if you were the author of the main article, and then you removed yourself as an admin, then you'll still be able to edit it.

Error comes when I did the following:
I created the main page with an admin, then tried to edit it with another admin.

**Comment by hrshtv** [comment]
Ah I see. 
Have you made that admin a superuser?

**Comment by DEVANSH-DVJ** [comment]
> Ah I see.
> Have you made that admin a superuser?
> 
> The error happens because:
> The edit button is visible to admins who have `is_admin` set as `True`.
> While, the ones who can actually access the edit page are the `superusers`.

The first admin is superuser while the second isn't. (actually it is by sso login, so not a superuser)

**Comment by DEVANSH-DVJ** [comment]
And never leave the else part.
If nothing is supposed to happened redirect it back but always put an else statement for every if (unless obvious)

**Comment by hrshtv** [comment]
Yes, actually I was leaving that for the end, but I'll fix that, and replace `is_superuser `by `is_admin` in all places necessary

**Pull request merged**
