### PR TITLE
Current website

### PR DESCRIPTION
**Pull request by hrshtv**
Branch for incorporating the changes of the current website.

### CODE REVIEW

**Comment by DEVANSH-DVJ** [comment]
image
Can you have blogBase and eventBase derived from mainBase?

**Comment by hrshtv** [comment]
Why? It's better to have separate navbars etc. 
We may need to customize it later catering to the needs of each app

**Comment by DEVANSH-DVJ** [comment]
> Why? It's better to have separate navbars etc.
> We may need to customize it later catering to the needs of each app

Ok, I agree.
At least add the required links in the navbar.

**Comment by DEVANSH-DVJ** [comment]
image

'Home' links to Blog home, can you change it to 'Blog Home' (or something better)... and add a link to homepage there as well (I know the one in the left links to homepage)..
Same goes for Events.
Just a suggestion.


Also, make 'About' page (or 'Instructions' page (for now copy the about page)) for blogs. (For general public)

**Comment by hrshtv** [comment]
> image
> 
> 'Home' links to Blog home, can you change it to 'Blog Home' (or something better)... and add a link to homepage there as well (I know the one in the left links to homepage)..
> Same goes for Events.
> Just a suggestion.

> Also, make 'About' page (or 'Instructions' page (for now copy the about page)) for blogs. (For general public)

I think it'll be better to do that at the end, when everything will be finalized.

**Pull request merged**
